### ISSUE TITLE
Reporting HTTP 302 as error is incorrect

### ISSUE THREAD

**Issue by mohawk2** [samrocketman/chewbotkah#4]
Further to our discussion on IRC, the software is treating (and reporting) 302 as an error. This is incorrect because per RFC 2616, 302 means ""the client SHOULD continue to use the Request-URI for future requests" (and has correctly found what it was looking for).

Therefore I would argue that as well as treating 200 as "all is well", 302 should also be treated this way.

**Comment by samrocketman** [comment]
Note to self.  Use something akin to the [java assertThat](http://stackoverflow.com/questions/6028750/how-to-assert-an-actual-value-against-2-or-more-expected-values).  Perhaps the [python assertIn](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIn) (available only in Python 2.7+).

**Comment by mohawk2** [comment]
Nice work!
